### ISSUE TITLE
data directory talks about Fermi not Chandra 

### ISSUE THREAD

**Issue by DougBurke** [adonath/snakemake-workflow-chandra#1]
From https://github.com/adonath/snakemake-workflow-chandra/blob/main/data/README.md I see a reference to fermi. Should it mention Chandra instead?

**Comment by adonath** [comment]
On Monday, April 15, 2024, Doug Burke ***@***.***> wrote:

> From https://github.com/adonath/snakemake-workflow-chandra/
> blob/main/data/README.md I see a reference to fermi. Should it mention
> Chandra instead?
>
Indeed! The link can actually be removed completely. Chandra data is
downloaded using the ciao tools.

**Comment by adonath** [comment]
Solved here https://github.com/adonath/snakemake-workflow-chandra/commit/2d74f06748af7f299db495f9d7ecb2cb3475fda4
